set_property MARK_DEBUG true [get_nets soc_dut_i/dutcomm_0_di_valid]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_dout[2]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_dout[1]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_din[3]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_din[2]}]
set_property MARK_DEBUG true [get_nets soc_dut_i/ctrlComm_0_di_ready]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_dout[3]}]
set_property MARK_DEBUG true [get_nets soc_dut_i/dutcomm_0_do_ready]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_din[1]}]
set_property MARK_DEBUG true [get_nets soc_dut_i/ctrlComm_0_do_valid]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_din[0]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_dout[0]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[1]}]
set_property MARK_DEBUG true [get_nets soc_dut_i/ctrlComm_0_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[7]}]
set_property MARK_DEBUG true [get_nets soc_dut_i/ctrlComm_0_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[15]}]
set_property MARK_DEBUG true [get_nets soc_dut_i/dutcomm_0/snd_start]

set_property MARK_DEBUG true [get_nets soc_dut_i/ctrlComm_0_M_AXIS_TLAST]

set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {soc_dut_i/dutcomm_0_M_AXIS_TDATA[16]}]
set_property MARK_DEBUG true [get_nets soc_dut_i/dutcomm_0_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets soc_dut_i/dutcomm_0_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets soc_dut_i/dutcomm_0_M_AXIS_TLAST]

set_property MARK_DEBUG true [get_nets soc_dut_i/ctrlComm_0/U0/res_ready]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list soc_dut_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 28 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {soc_dut_i/dutcomm_0_M_AXIS_TDATA[4]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[5]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[6]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[7]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[8]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[9]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[10]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[11]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[12]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[13]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[14]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[15]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[16]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[17]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[18]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[19]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[20]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[21]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[22]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[23]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[24]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[25]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[26]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[27]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[28]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[29]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[30]} {soc_dut_i/dutcomm_0_M_AXIS_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {soc_dut_i/dutcomm_0_din[0]} {soc_dut_i/dutcomm_0_din[1]} {soc_dut_i/dutcomm_0_din[2]} {soc_dut_i/dutcomm_0_din[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {soc_dut_i/ctrlComm_0_dout[0]} {soc_dut_i/ctrlComm_0_dout[1]} {soc_dut_i/ctrlComm_0_dout[2]} {soc_dut_i/ctrlComm_0_dout[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[0]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[1]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[2]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[3]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[4]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[5]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[6]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[7]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[8]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[9]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[10]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[11]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[12]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[13]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[14]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[15]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[16]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[17]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[18]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[19]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[20]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[21]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[22]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[23]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[24]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[25]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[26]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[27]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[28]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[29]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[30]} {soc_dut_i/ctrlComm_0_M_AXIS_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list soc_dut_i/ctrlComm_0_di_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list soc_dut_i/ctrlComm_0_do_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list soc_dut_i/ctrlComm_0_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list soc_dut_i/ctrlComm_0_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list soc_dut_i/ctrlComm_0_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list soc_dut_i/dutcomm_0_di_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list soc_dut_i/dutcomm_0_do_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list soc_dut_i/dutcomm_0_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list soc_dut_i/dutcomm_0_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list soc_dut_i/dutcomm_0_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list soc_dut_i/ctrlComm_0/U0/res_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list soc_dut_i/dutcomm_0/snd_start]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK1]
