#
# Vivado (TM) v2017.2 (64-bit)
#
# build_proj.tcl: Tcl script for re-creating project 'soc_dut'
#
# Generated by Vivado on Wed Dec 19 17:17:48 EST 2018
# IP Build 1909766 on Thu Jun 15 19:58:00 MDT 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build_proj.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/sources/soc_dut/vivado/soc_dut/soc_dut.srcs/sources_1/imports/hdl/soc_dut_wrapper.vhd"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/aes_non_pipe.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/controller.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/datapath.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/registern.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/sbox.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/upcount.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/aes_axi.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/sources/soc_dut/vivado/soc_dut/soc_dut.srcs/sources_1/bd/soc_dut/soc_dut.bd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/aes_tb.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/packages.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/examples/AES-128/vhdl/register8.vhd"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/sources/soc_dut/vivado/src/constr/zybo.xdc"
#    "/nhome/aabdulga/repos/fobos_soc_proj/fobos/sources/soc_dut/vivado/src/constr/ext_debug.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "build_proj.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/soc_dut"]"

# Create project
create_project soc_dut ./soc_dut -part xc7z010clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects soc_dut]
set_property -name "board_part" -value "digilentinc.com:zybo:part0:1.0" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/soc_dut.cache/ip" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/ip_repo"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/aes_non_pipe.vhd"]"\
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/controller.vhd"]"\
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/datapath.vhd"]"\
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/registern.vhd"]"\
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/sbox.vhd"]"\
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/upcount.vhd"]"\
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/aes_axi.vhd"]"\
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/aes_tb.vhd"]"\
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/packages.vhd"]"\
 "[file normalize "$origin_dir/../../../examples/AES-128/vhdl/register8.vhd"]"\
]
add_files -norecurse -fileset $obj $files



# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../../examples/AES-128/vhdl/aes_non_pipe.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../examples/AES-128/vhdl/controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../examples/AES-128/vhdl/datapath.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../examples/AES-128/vhdl/registern.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../examples/AES-128/vhdl/sbox.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../examples/AES-128/vhdl/upcount.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../examples/AES-128/vhdl/aes_axi.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../examples/AES-128/vhdl/aes_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../examples/AES-128/vhdl/packages.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../examples/AES-128/vhdl/register8.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj






# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/constr/zybo.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/src/constr/zybo.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/constr/ext_debug.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/src/constr/ext_debug.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/src/constr/ext_debug.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)



# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z010clg400-1 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property -name "steps.synth_design.args.flatten_hierarchy" -value "none" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z010clg400-1 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:soc_dut"


######ADDED
# Create block design
 source $origin_dir/src/bd/top.tcl

 # Generate the wrapper
 set design_name [get_bd_designs]
 make_wrapper -files [get_files $design_name.bd] -top -import
#####END ADDED
