--------------------------------------------------------------------------------
-- Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.1
--  \   \         Application : xaw2vhdl
--  /   /         Filename : DCM.vhd
-- /___/   /\     Timestamp : 10/09/2012 07:26:44
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st C:\xilinx_projects\test3\ipcore_dir\.\DCM.xaw C:\xilinx_projects\test3\ipcore_dir\.\DCM
--Design Name: DCM
--Device: xc3s500e-4fg320
--
-- Module DCM
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity dcm_core_500KHz is
   port ( CLKIN_IN        : in    std_logic; 
          RST_IN          : in    std_logic; 
          CLK500KHz_OUT   : out   std_logic; 
          LOCKED_OUT      : out   std_logic);
end dcm_core_500KHz;

architecture BEHAVIORAL of dcm_core_500KHz is
   signal CLKFB_IN , CLKFB_IN1      : std_logic;
   signal LOCKED_OUT1,LOCKED_OUT2   : std_logic;
   signal CLKIN_IBUFG     			: std_logic;
   signal CLK0_BUF ,CLK0_BUF1		: std_logic;
   signal CLK5MHz_BUF       		: std_logic;
   signal CLK500KHz_BUF      		: std_logic;
   signal GND_BIT         			: std_logic;
begin
	GND_BIT <= '0';
	
	CLKIN_IBUFG <= CLKIN_IN;
   
	CLK0_BUFG_INST : BUFG
      port map (I=>CLK0_BUF,
                O=>CLKFB_IN);
   
	CLK0_BUFG_INST1 : BUFG
      port map (I=>CLK0_BUF1,
                O=>CLKFB_IN1);
	
	CLK500_BUFG_INST : BUFG
      port map (I=>CLK500KHz_BUF,
                O=>CLK500KHz_OUT);
				
   DCM_SP_INST : DCM_SP
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 10.0,
            CLKFX_DIVIDE => 20,
            CLKFX_MULTIPLY => 2,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 20.000,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"C080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>CLKFB_IN,
                CLKIN=>CLKIN_IBUFG,
                DSSEN=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>RST_IN,
                CLKDV=>CLK5MHz_BUF,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>CLK0_BUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>LOCKED_OUT1,
                PSDONE=>open,
                STATUS=>open);
      
					 
	DCM_SP_INST1 : DCM_SP
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 10.0,
            CLKFX_DIVIDE => 20,
            CLKFX_MULTIPLY => 2,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 20.000,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"C080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>CLKFB_IN1,
                CLKIN=>CLK5MHz_BUF,
                DSSEN=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>RST_IN,
                CLKDV=>CLK500KHz_BUF,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>CLK0_BUF1,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>LOCKED_OUT2,
                PSDONE=>open,
                STATUS=>open);
				
	LOCKED_OUT <= LOCKED_OUT1 and LOCKED_OUT2;
	
end BEHAVIORAL;


