#!/usr/bin/python

CONFIGFILENAME = "analysis_config.txt"
CONFIG_FILE = ""
ROOTDIR = ""
TESTDIRNAME = "testing"
TESTDIR = ""

PROCESS_MODULE_OUTPUT_FILE_NAME = "ProcessedData.dat"
PROCESS_COMPRESS_MODULE_OUTPUT_FILE_NAME = "ProcessedAndCompressedData.dat"
COMPRESS_MODULE_OUTPUT_FILE_NAME = "CompressedData.dat"
PROCESS_MODULE_INPUT_FILE = ""
COMPRESS_MODULE_INPUT_FILE = ""
PROCESS_MODULE_OUTPUT_FILE = ""
COMPRESS_MODULE_OUTPUT_FILE = ""






analysisConfigAttributes = {
'SAMPLE_WINDOW' : "", 'WINDOW_START_POINT' : "", 'CAPTURE_MODE' : "",
'COMPRESSION_LENGTH' : "", 'COMPRESSION_TYPE' : "", 'TRIGGER_THRESHOLD': "",
'PROCESS_DATA' : "", 'COMPRESS_DATA' : "", 'CORRELATION_PEARSONS' : "",
}