[[design]]
name = "fobos_dut"
dependencies = [
    { base_uri = "https://github.com/GMUCERG/TinyJAMBU-SCA.git#dev", design_file = "./TinyJAMBU-DOM1-v1.toml" },
]


rtl.sources = [
    "src_rtl/LFSR.vhd",
    "src_rtl/asym_fifo.vhd",
    "src_rtl/LWC_SCA_wrapper.vhd",
    "src_rtl/core_wrapper.vhd",
    "src_rtl/half_duplex_interface.vhd",
    "src_rtl/half_duplex_dut.vhd",
]
# includes = []
rtl.top = "half_duplex_dut"
rtl.clocks.sys_clk.port = "clk_c2d"

# clock.port = "clk"
# reset.port = "reset"
# reset.active_high = true
# reset.asynchronous = false
rtl.parameters = { W = 256, SW = 128 }

language.vhdl.version = "2008"
# vhdl.synopsys = false
# verilog.version = "2001"
# systemverilog.version = "2009"

tb.sources = [
    "src_tb/core_wrapper_tb.vhd",
    # "src_tb/LWC_TB_SCA_wrapper_conf.vhd",
]
tb.top = "core_wrapper_tb"
# top = "LWC_TB_SCA_wrapper_conf"
# includes = []

[design.tb.parameters]
# {file: "xx"} is an extension to specify a string generic/parameter pointing to a relative path:
G_CONFIG_FNAME = { file = "./configFile.txt" }
G_DIN_FNAME = { file = "FOBOS_KAT/TinyJAMBU-DOM1-v1/dinFile.txt" }
G_DOUT_FNAME = { path = "./doutFile.txt" }
# G_FNAME_SDI = { file = "KAT/TinyJAMBU-DOM1-v1/sdi_shared_2.txt" }
# G_FNAME_RDI = { file = "KAT/TinyJAMBU-DOM1-v1/rdi.txt" }
# G_FNAME_DO = { file = "KAT/TinyJAMBU-DOM1-v1/do.txt" }
# G_TEST_MODE = 0 # 1: stall inputs and outputs
# G_RANDOM_STALL = true
# G_TIMEOUT_CYCLES = 1000
# G_MAX_FAILURES = 0

[design.lwc.aead]
algorithm = "tinyjambu128"
# key_bits = 128
# npub_bits = 128
# tag_bits = 128
# input_sequence.encrypt = [ "npub", "ad", "pt", "tag" ]
# input_sequence.decrypt = [ "npub", "ad", "ct", "tag" ]

# [lwc.hash]
# algorithm = "" ###### (hashing is not supported)
# digest_bits = 128

[design.lwc.ports]
# pdi.bit_width = 32
# pdi.num_shares = 2
# rdi.bit_width = 192
# # sdi.bit_width = 32
# sdi.num_shares = 2

[design.lwc.sca_protection]
target = ["timing", "sda", "dpa"]
order = 1

[flows.vivado_synth]
fpga.part = "xc7a100tftg256-3"
xdc_files = ["constraints/cw305.xdc"]
clocks.sys_clk.port = "clk_c2d"
clocks.sys_clk.freq = 50
synth.strategy = "Flow_AreaOptimized_high"
impl.strategy = "Area_ExploreWithRemap"
optimize_power = true
optimize_power_postplace = true
write_bitstream = true
qor_suggestions = true
