##set_property MARK_DEBUG true [get_nets {din_OBUF[0]}]
##set_property MARK_DEBUG true [get_nets do_ready_OBUF]
##set_property MARK_DEBUG true [get_nets di_valid_OBUF]
##set_property MARK_DEBUG true [get_nets di_ready_IBUF]
##set_property MARK_DEBUG true [get_nets {dout_IBUF[1]}]
##set_property MARK_DEBUG true [get_nets {dout_IBUF[2]}]
##set_property MARK_DEBUG true [get_nets {din_OBUF[1]}]
##set_property MARK_DEBUG true [get_nets {dout_IBUF[3]}]
##set_property MARK_DEBUG true [get_nets reset_IBUF]
##set_property MARK_DEBUG true [get_nets {din_OBUF[3]}]
##set_property MARK_DEBUG true [get_nets dut_clk_OBUF]
##set_property MARK_DEBUG true [get_nets do_valid_IBUF]
##set_property MARK_DEBUG true [get_nets {din_OBUF[2]}]
##set_property MARK_DEBUG true [get_nets {dout_IBUF[0]}]
##connect_debug_port u_ila_0/clk [get_nets [list top_i/clk_wiz_1/inst/clkfbout_buf_top_clk_wiz_1_1]]


##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[13]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[11]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[23]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[21]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[20]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[31]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[18]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[17]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[22]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[15]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[8]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[3]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[25]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[1]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[5]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[6]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[14]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[12]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[10]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[19]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[28]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[2]}]
##set_property MARK_DEBUG true [get_nets top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TVALID]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[24]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[16]}]
##set_property MARK_DEBUG true [get_nets top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TREADY]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[9]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[30]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[26]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[0]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[4]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[27]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[29]}]
##set_property MARK_DEBUG true [get_nets {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[7]}]
##create_debug_core u_ila_0 ila
##set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
##set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
##set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
##set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
##set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
##set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
##set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
##set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
##set_property port_width 1 [get_debug_ports u_ila_0/clk]
##connect_debug_port u_ila_0/clk [get_nets [list top_i/clk_wiz_1/inst/clk_slow]]
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
##set_property port_width 4 [get_debug_ports u_ila_0/probe0]
##connect_debug_port u_ila_0/probe0 [get_nets [list {din_OBUF[0]} {din_OBUF[1]} {din_OBUF[2]} {din_OBUF[3]}]]
##create_debug_port u_ila_0 probe
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
##set_property port_width 4 [get_debug_ports u_ila_0/probe1]
##connect_debug_port u_ila_0/probe1 [get_nets [list {dout_IBUF[0]} {dout_IBUF[1]} {dout_IBUF[2]} {dout_IBUF[3]}]]
##create_debug_port u_ila_0 probe
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
##set_property port_width 32 [get_debug_ports u_ila_0/probe2]
##connect_debug_port u_ila_0/probe2 [get_nets [list {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[0]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[1]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[2]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[3]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[4]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[5]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[6]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[7]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[8]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[9]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[10]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[11]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[12]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[13]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[14]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[15]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[16]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[17]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[18]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[19]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[20]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[21]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[22]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[23]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[24]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[25]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[26]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[27]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[28]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[29]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[30]} {top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TDATA[31]}]]
##create_debug_port u_ila_0 probe
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
##set_property port_width 1 [get_debug_ports u_ila_0/probe3]
##connect_debug_port u_ila_0/probe3 [get_nets [list top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TREADY]]
##create_debug_port u_ila_0 probe
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
##set_property port_width 1 [get_debug_ports u_ila_0/probe4]
##connect_debug_port u_ila_0/probe4 [get_nets [list top_i/axi_fifo_mm_s_0_AXI_STR_TXD_TVALID]]
##create_debug_port u_ila_0 probe
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
##set_property port_width 1 [get_debug_ports u_ila_0/probe5]
##connect_debug_port u_ila_0/probe5 [get_nets [list di_ready_IBUF]]
##create_debug_port u_ila_0 probe
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
##set_property port_width 1 [get_debug_ports u_ila_0/probe6]
##connect_debug_port u_ila_0/probe6 [get_nets [list di_valid_OBUF]]
##create_debug_port u_ila_0 probe
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
##set_property port_width 1 [get_debug_ports u_ila_0/probe7]
##connect_debug_port u_ila_0/probe7 [get_nets [list do_ready_OBUF]]
##create_debug_port u_ila_0 probe
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
##set_property port_width 1 [get_debug_ports u_ila_0/probe8]
##connect_debug_port u_ila_0/probe8 [get_nets [list do_valid_IBUF]]
##create_debug_port u_ila_0 probe
##set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
##set_property port_width 1 [get_debug_ports u_ila_0/probe9]
##connect_debug_port u_ila_0/probe9 [get_nets [list reset_IBUF]]

##set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/dut_working]
##set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/dut_rst]
##set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/snd_start]

##set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/timeoutmod/op_done]
##set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/timeoutmod/timedout]
##set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/op_done]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[0]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[3]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[22]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[9]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[21]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[15]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[30]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[19]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[10]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[7]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[12]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[26]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[13]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[2]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[16]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[24]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[8]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[29]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[6]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[11]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[27]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[28]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[14]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[5]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[31]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[20]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[17]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[4]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[23]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[1]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[18]}]
##set_property MARK_DEBUG false [get_nets {top_i/dut_controller_0/U0/timeout[25]}]
##set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
##set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
##set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
##connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_slow]

#set_property MARK_DEBUG true [get_nets di_ready_IBUF]
#set_property MARK_DEBUG true [get_nets di_valid_OBUF]
#set_property MARK_DEBUG true [get_nets {din_OBUF[0]}]
#set_property MARK_DEBUG true [get_nets {din_OBUF[1]}]
#set_property MARK_DEBUG true [get_nets {din_OBUF[2]}]
#set_property MARK_DEBUG true [get_nets {din_OBUF[3]}]
#set_property MARK_DEBUG true [get_nets do_ready_OBUF]
#set_property MARK_DEBUG true [get_nets do_valid_IBUF]
#set_property MARK_DEBUG true [get_nets {dout_IBUF[0]}]
#set_property MARK_DEBUG true [get_nets {dout_IBUF[1]}]
#set_property MARK_DEBUG true [get_nets {dout_IBUF[2]}]
#set_property MARK_DEBUG true [get_nets {dout_IBUF[3]}]
#set_property MARK_DEBUG true [get_nets dut_rst_OBUF]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[0]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[10]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[11]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[12]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[13]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[14]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[15]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[16]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[17]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[18]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[19]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[1]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[20]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[21]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[22]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[23]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[24]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[25]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[26]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[27]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[28]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[29]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[2]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[30]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[31]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[3]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[4]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[5]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[6]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[7]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[8]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout[9]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout_status[0]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout_status[1]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout_status[2]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout_status[3]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout_status[4]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout_status[5]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout_status[6]}]
#set_property MARK_DEBUG true [get_nets {top_i/d_timeout_status[7]}]
#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/dut_working]
#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/op_done]
#set_property MARK_DEBUG true [get_nets top_i/dutcomm_0_snd_start]
#connect_debug_port u_ila_0/probe10 [get_nets [list top_i/dutcomm_0_snd_start]]

#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/dut_rst]
#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/snd_start]




#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/dut_controller_v1_0_S_AXI_inst/d_timeout_ack]
#connect_debug_port u_ila_0/probe4 [get_nets [list top_i/dut_controller_0/U0/dut_controller_v1_0_S_AXI_inst/d_timeout_ack]]


#set_property MARK_DEBUG true [get_nets top_i/d_timeout_ack]



#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/timeoutmod/en_timeout_cnt]

#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/timeoutmod/snd_start]
#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/timeoutmod/timedout]

#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/d_en_module]
#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/d_timeout_ack]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[0]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[10]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[11]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[12]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[13]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[14]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[15]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[16]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[17]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[18]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[19]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[1]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[20]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[21]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[22]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[23]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[24]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[25]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[26]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[27]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[28]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[29]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[2]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[30]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[31]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[3]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[4]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[5]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[6]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[7]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[8]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/d_timeout_cnt[9]}]
#set_property MARK_DEBUG true [get_nets top_i/dut_rst]


#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/d_en_module]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][0]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][10]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][11]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][12]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][13]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][14]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][15]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][16]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][17]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][18]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][19]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][1]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][20]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][21]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][22]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][23]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][24]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][25]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][26]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][27]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][28]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][29]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][2]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][30]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][31]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][3]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][4]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][5]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][6]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][7]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][8]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout[31][9]}]
#set_property MARK_DEBUG true [get_nets top_i/dut_controller_0/U0/d_timeout_ack]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[0]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[10]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[11]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[12]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[13]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[14]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[15]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[16]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[17]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[18]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[19]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[1]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[20]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[21]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[22]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[23]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[24]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[25]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[26]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[27]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[28]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[29]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[2]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[30]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[31]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[3]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[4]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[5]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[6]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[7]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[8]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_cnt[9]}]
#set_property MARK_DEBUG true [get_nets {top_i/dut_controller_0/U0/d_timeout_status[0]}]
#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list top_i/clk_wiz_1/inst/clk_slow]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 4 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {din_OBUF[0]} {din_OBUF[1]} {din_OBUF[2]} {din_OBUF[3]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 4 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {dout_IBUF[0]} {dout_IBUF[1]} {dout_IBUF[2]} {dout_IBUF[3]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 32 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {top_i/dut_controller_0/d_timeout_cnt[0]} {top_i/dut_controller_0/d_timeout_cnt[1]} {top_i/dut_controller_0/d_timeout_cnt[2]} {top_i/dut_controller_0/d_timeout_cnt[3]} {top_i/dut_controller_0/d_timeout_cnt[4]} {top_i/dut_controller_0/d_timeout_cnt[5]} {top_i/dut_controller_0/d_timeout_cnt[6]} {top_i/dut_controller_0/d_timeout_cnt[7]} {top_i/dut_controller_0/d_timeout_cnt[8]} {top_i/dut_controller_0/d_timeout_cnt[9]} {top_i/dut_controller_0/d_timeout_cnt[10]} {top_i/dut_controller_0/d_timeout_cnt[11]} {top_i/dut_controller_0/d_timeout_cnt[12]} {top_i/dut_controller_0/d_timeout_cnt[13]} {top_i/dut_controller_0/d_timeout_cnt[14]} {top_i/dut_controller_0/d_timeout_cnt[15]} {top_i/dut_controller_0/d_timeout_cnt[16]} {top_i/dut_controller_0/d_timeout_cnt[17]} {top_i/dut_controller_0/d_timeout_cnt[18]} {top_i/dut_controller_0/d_timeout_cnt[19]} {top_i/dut_controller_0/d_timeout_cnt[20]} {top_i/dut_controller_0/d_timeout_cnt[21]} {top_i/dut_controller_0/d_timeout_cnt[22]} {top_i/dut_controller_0/d_timeout_cnt[23]} {top_i/dut_controller_0/d_timeout_cnt[24]} {top_i/dut_controller_0/d_timeout_cnt[25]} {top_i/dut_controller_0/d_timeout_cnt[26]} {top_i/dut_controller_0/d_timeout_cnt[27]} {top_i/dut_controller_0/d_timeout_cnt[28]} {top_i/dut_controller_0/d_timeout_cnt[29]} {top_i/dut_controller_0/d_timeout_cnt[30]} {top_i/dut_controller_0/d_timeout_cnt[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 32 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list {top_i/dut_controller_0/U0/d_timeout_cnt[0]} {top_i/dut_controller_0/U0/d_timeout_cnt[1]} {top_i/dut_controller_0/U0/d_timeout_cnt[2]} {top_i/dut_controller_0/U0/d_timeout_cnt[3]} {top_i/dut_controller_0/U0/d_timeout_cnt[4]} {top_i/dut_controller_0/U0/d_timeout_cnt[5]} {top_i/dut_controller_0/U0/d_timeout_cnt[6]} {top_i/dut_controller_0/U0/d_timeout_cnt[7]} {top_i/dut_controller_0/U0/d_timeout_cnt[8]} {top_i/dut_controller_0/U0/d_timeout_cnt[9]} {top_i/dut_controller_0/U0/d_timeout_cnt[10]} {top_i/dut_controller_0/U0/d_timeout_cnt[11]} {top_i/dut_controller_0/U0/d_timeout_cnt[12]} {top_i/dut_controller_0/U0/d_timeout_cnt[13]} {top_i/dut_controller_0/U0/d_timeout_cnt[14]} {top_i/dut_controller_0/U0/d_timeout_cnt[15]} {top_i/dut_controller_0/U0/d_timeout_cnt[16]} {top_i/dut_controller_0/U0/d_timeout_cnt[17]} {top_i/dut_controller_0/U0/d_timeout_cnt[18]} {top_i/dut_controller_0/U0/d_timeout_cnt[19]} {top_i/dut_controller_0/U0/d_timeout_cnt[20]} {top_i/dut_controller_0/U0/d_timeout_cnt[21]} {top_i/dut_controller_0/U0/d_timeout_cnt[22]} {top_i/dut_controller_0/U0/d_timeout_cnt[23]} {top_i/dut_controller_0/U0/d_timeout_cnt[24]} {top_i/dut_controller_0/U0/d_timeout_cnt[25]} {top_i/dut_controller_0/U0/d_timeout_cnt[26]} {top_i/dut_controller_0/U0/d_timeout_cnt[27]} {top_i/dut_controller_0/U0/d_timeout_cnt[28]} {top_i/dut_controller_0/U0/d_timeout_cnt[29]} {top_i/dut_controller_0/U0/d_timeout_cnt[30]} {top_i/dut_controller_0/U0/d_timeout_cnt[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 32 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list {top_i/dut_controller_0/U0/d_timeout[31][0]} {top_i/dut_controller_0/U0/d_timeout[31][1]} {top_i/dut_controller_0/U0/d_timeout[31][2]} {top_i/dut_controller_0/U0/d_timeout[31][3]} {top_i/dut_controller_0/U0/d_timeout[31][4]} {top_i/dut_controller_0/U0/d_timeout[31][5]} {top_i/dut_controller_0/U0/d_timeout[31][6]} {top_i/dut_controller_0/U0/d_timeout[31][7]} {top_i/dut_controller_0/U0/d_timeout[31][8]} {top_i/dut_controller_0/U0/d_timeout[31][9]} {top_i/dut_controller_0/U0/d_timeout[31][10]} {top_i/dut_controller_0/U0/d_timeout[31][11]} {top_i/dut_controller_0/U0/d_timeout[31][12]} {top_i/dut_controller_0/U0/d_timeout[31][13]} {top_i/dut_controller_0/U0/d_timeout[31][14]} {top_i/dut_controller_0/U0/d_timeout[31][15]} {top_i/dut_controller_0/U0/d_timeout[31][16]} {top_i/dut_controller_0/U0/d_timeout[31][17]} {top_i/dut_controller_0/U0/d_timeout[31][18]} {top_i/dut_controller_0/U0/d_timeout[31][19]} {top_i/dut_controller_0/U0/d_timeout[31][20]} {top_i/dut_controller_0/U0/d_timeout[31][21]} {top_i/dut_controller_0/U0/d_timeout[31][22]} {top_i/dut_controller_0/U0/d_timeout[31][23]} {top_i/dut_controller_0/U0/d_timeout[31][24]} {top_i/dut_controller_0/U0/d_timeout[31][25]} {top_i/dut_controller_0/U0/d_timeout[31][26]} {top_i/dut_controller_0/U0/d_timeout[31][27]} {top_i/dut_controller_0/U0/d_timeout[31][28]} {top_i/dut_controller_0/U0/d_timeout[31][29]} {top_i/dut_controller_0/U0/d_timeout[31][30]} {top_i/dut_controller_0/U0/d_timeout[31][31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 1 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list {top_i/dut_controller_0/U0/d_timeout_status[0]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 32 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list {top_i/d_timeout[0]} {top_i/d_timeout[1]} {top_i/d_timeout[2]} {top_i/d_timeout[3]} {top_i/d_timeout[4]} {top_i/d_timeout[5]} {top_i/d_timeout[6]} {top_i/d_timeout[7]} {top_i/d_timeout[8]} {top_i/d_timeout[9]} {top_i/d_timeout[10]} {top_i/d_timeout[11]} {top_i/d_timeout[12]} {top_i/d_timeout[13]} {top_i/d_timeout[14]} {top_i/d_timeout[15]} {top_i/d_timeout[16]} {top_i/d_timeout[17]} {top_i/d_timeout[18]} {top_i/d_timeout[19]} {top_i/d_timeout[20]} {top_i/d_timeout[21]} {top_i/d_timeout[22]} {top_i/d_timeout[23]} {top_i/d_timeout[24]} {top_i/d_timeout[25]} {top_i/d_timeout[26]} {top_i/d_timeout[27]} {top_i/d_timeout[28]} {top_i/d_timeout[29]} {top_i/d_timeout[30]} {top_i/d_timeout[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 8 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list {top_i/d_timeout_status[0]} {top_i/d_timeout_status[1]} {top_i/d_timeout_status[2]} {top_i/d_timeout_status[3]} {top_i/d_timeout_status[4]} {top_i/d_timeout_status[5]} {top_i/d_timeout_status[6]} {top_i/d_timeout_status[7]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
#set_property port_width 1 [get_debug_ports u_ila_0/probe8]
#connect_debug_port u_ila_0/probe8 [get_nets [list top_i/dut_controller_0/d_en_module]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
#set_property port_width 1 [get_debug_ports u_ila_0/probe9]
#connect_debug_port u_ila_0/probe9 [get_nets [list top_i/dut_controller_0/U0/d_en_module]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
#set_property port_width 1 [get_debug_ports u_ila_0/probe10]
#connect_debug_port u_ila_0/probe10 [get_nets [list top_i/d_timeout_ack]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
#set_property port_width 1 [get_debug_ports u_ila_0/probe11]
#connect_debug_port u_ila_0/probe11 [get_nets [list top_i/dut_controller_0/U0/d_timeout_ack]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
#set_property port_width 1 [get_debug_ports u_ila_0/probe12]
#connect_debug_port u_ila_0/probe12 [get_nets [list di_ready_IBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
#set_property port_width 1 [get_debug_ports u_ila_0/probe13]
#connect_debug_port u_ila_0/probe13 [get_nets [list di_valid_OBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
#set_property port_width 1 [get_debug_ports u_ila_0/probe14]
#connect_debug_port u_ila_0/probe14 [get_nets [list do_ready_OBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
#set_property port_width 1 [get_debug_ports u_ila_0/probe15]
#connect_debug_port u_ila_0/probe15 [get_nets [list do_valid_IBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
#set_property port_width 1 [get_debug_ports u_ila_0/probe16]
#connect_debug_port u_ila_0/probe16 [get_nets [list top_i/dut_rst]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
#set_property port_width 1 [get_debug_ports u_ila_0/probe17]
#connect_debug_port u_ila_0/probe17 [get_nets [list dut_rst_OBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
#set_property port_width 1 [get_debug_ports u_ila_0/probe18]
#connect_debug_port u_ila_0/probe18 [get_nets [list top_i/dut_controller_0/dut_working]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
#set_property port_width 1 [get_debug_ports u_ila_0/probe19]
#connect_debug_port u_ila_0/probe19 [get_nets [list top_i/dut_controller_0/U0/timeoutmod/en_timeout_cnt]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
#set_property port_width 1 [get_debug_ports u_ila_0/probe20]
#connect_debug_port u_ila_0/probe20 [get_nets [list top_i/dut_controller_0/op_done]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
#set_property port_width 1 [get_debug_ports u_ila_0/probe21]
#connect_debug_port u_ila_0/probe21 [get_nets [list top_i/dut_controller_0/snd_start]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
#set_property port_width 1 [get_debug_ports u_ila_0/probe22]
#connect_debug_port u_ila_0/probe22 [get_nets [list top_i/dut_controller_0/U0/timeoutmod/timedout]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_slow]

set_property MARK_DEBUG true [get_nets do_ready_OBUF]
set_property MARK_DEBUG true [get_nets {dut_clk_OBUF[0]}]
set_property MARK_DEBUG true [get_nets dut_rst_OBUF]
set_property MARK_DEBUG true [get_nets {dout_IBUF[3]}]
set_property MARK_DEBUG true [get_nets {dout_IBUF[0]}]
set_property MARK_DEBUG true [get_nets di_ready_IBUF]
set_property MARK_DEBUG true [get_nets di_valid_OBUF]
set_property MARK_DEBUG true [get_nets {dout_IBUF[1]}]
set_property MARK_DEBUG true [get_nets do_valid_IBUF]
set_property MARK_DEBUG true [get_nets {dout_IBUF[2]}]
set_property MARK_DEBUG true [get_nets trigger_out_OBUF]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list top_i/clk_wiz_0/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dout_IBUF[0]} {dout_IBUF[1]} {dout_IBUF[2]} {dout_IBUF[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {dut_clk_OBUF[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list di_ready_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list di_valid_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list do_ready_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list do_valid_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list dut_rst_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list trigger_out_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out2]
