set_property MARK_DEBUG true [get_nets {din_OBUF[0]}]
set_property MARK_DEBUG true [get_nets do_ready_OBUF]
set_property MARK_DEBUG true [get_nets di_valid_OBUF]
set_property MARK_DEBUG true [get_nets di_ready_IBUF]
set_property MARK_DEBUG true [get_nets {dout_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {dout_IBUF[2]}]
set_property MARK_DEBUG true [get_nets {din_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {dout_IBUF[3]}]
set_property MARK_DEBUG true [get_nets reset_IBUF]
set_property MARK_DEBUG true [get_nets {din_OBUF[3]}]
set_property MARK_DEBUG true [get_nets dut_clk_OBUF]
set_property MARK_DEBUG true [get_nets do_valid_IBUF]
set_property MARK_DEBUG true [get_nets {din_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {dout_IBUF[0]}]
connect_debug_port u_ila_0/clk [get_nets [list top_i/clk_wiz_1/inst/clkfbout_buf_top_clk_wiz_1_1]]

